version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      production:
        dependency-type: production
      dev:
        dependency-type: development
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "ci"
    open-pull-requests-limit: 5
